<?php
// @codingStandardsIgnoreStart
/**
 * @var $block \Magedelight\Authorizecim\Block\Customer\Cards\Edit
 */
$code = \Magedelight\Authorizecim\Model\Payment::METHOD_CODE;
$customHelper = $block->helper(Magedelight\Authorizecim\Helper\Data::class);
$authorizeCIMIsEnabled = $customHelper->getConfig('payment/md_authorizecim/active');
if ($authorizeCIMIsEnabled == 1) { ?>
    <?php $card = $block->getCard(); ?>
    <form class="form-card-edit"
          action="<?= $block->escapeHtml($block->getSaveUrl()) ?>"
          method="post" id="form-validate"
          data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
        <fieldset class="fieldset">
            <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend><br>
            <?= $block->getBlockHtml('formkey')?>
            <div class="field <?= $block->escapeHtml($code) ?>_firstname required">
                <label class="label" for="<?= $block->escapeHtml($code) ?>_firstname">
                    <span><?= $block->escapeHtml(__('First Name')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="<?= $block->escapeHtml($code) ?>[address_info][firstname]"
                           id="<?= $block->escapeHtml($code) ?>_firstname"
                           title="<?= $block->escapeHtml(__('First Name')) ?>"
                           value="<?= $block->escapeHtml($card['firstname']) ?>"
                           class="input-text required-entry">
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_lastname required">
                <label class="label" for="<?= $block->escapeHtml($code) ?>_lastname">
                    <span><?= $block->escapeHtml(__('Last Name')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="<?= $block->escapeHtml($code) ?>[address_info][lastname]"
                           id="<?= $block->escapeHtml($code) ?>_lastname"
                           title="<?= $block->escapeHtml(__('Last Name')) ?>"
                           value="<?= $block->escapeHtml($card['lastname']) ?>"
                           class="input-text required-entry">
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_company">
                <label class="label" for="<?= $block->escapeHtml($code) ?>_company">
                    <span><?= $block->escapeHtml(__('Company')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="<?= $block->escapeHtml($code) ?>[address_info][company]"
                           id="<?= $block->escapeHtml($code) ?>_company"
                           title="<?= $block->escapeHtml(__('Company')) ?>"
                           value="<?= $block->escapeHtml($card['company']) ?>"
                           class="input-text ">
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_street required">
                <label for="<?= $block->escapeHtml($code) ?>_street" class="label">
                    <span><?= $block->escapeHtml(__('Street Address')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="<?= $block->escapeHtml($code) ?>[address_info][street]"
                           value="<?= $block->escapeHtml($card['street']) ?>"
                           title="<?= /* @noEscape */ __('Street Address') ?>"
                           id="<?= $block->escapeHtml($code) ?>_street"
                           class="input-text required-entry"  />
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_city required">
                <label class="label" for="<?= $block->escapeHtml($code) ?>_city">
                    <span><?= /* @noEscape */ __('City') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="<?= $block->escapeHtml($code) ?>[address_info][city]"
                           value="<?= $block->escapeHtml($card['city']) ?>"
                           title="<?= $block->escapeHtml(__('City')) ?>"
                           class="input-text required-entry"
                           id="<?= $block->escapeHtml($code) ?>_city">
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_region required">
                <label class="label" for="<?= $block->escapeHtml($code) ?>_region_id">
                    <span><?= /* @noEscape */ __('State/Province') ?></span>
                </label>
                <div class="control">
                    <select id="<?= $block->escapeHtml($code) ?>_region_id"
                            name="<?= $block->escapeHtml($code) ?>[address_info][region_id]"
                            title="<?= /* @noEscape */ __('State/Province') ?>"
                            class="validate-select">
                        <option value="">
                            <?= /* @noEscape */ __('Please select a region, state or province.') ?>
                        </option>
                    </select>
                    <input type="text"
                           id="<?= $block->escapeHtml($code) ?>_region"
                           name="<?= $block->escapeHtml($code) ?>[address_info][state]"
                           value="<?= $block->escapeHtml($card['state']) ?>"
                           title="<?= /* @noEscape */ __('State/Province') ?>"
                           class="input-text " />
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_postcode required">
                <label class="label" for="postcode"><span><?= /* @noEscape */ __('Zip/Postal Code') ?></span></label>
                <div class="control">
                    <input type="text"
                           name="<?= $block->escapeHtml($code) ?>[address_info][postcode]"
                           value="<?= $block->escapeHtml($card['postcode']) ?>"
                           title="<?= /* @noEscape */ __('Zip/Postal Code') ?>"
                           id="<?= $block->escapeHtml($code) ?>_postcode"
                           class="input-text required-entry validate-zip-international ">
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_country_id required">
                <label class="label" for="country"><span><?= /* @noEscape */ __('Country') ?></span></label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect($card['country_id']) ?>
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_telephone">
                <label class="label" for="<?= $block->escapeHtml($code) ?>_telephone">
                    <span><?= /* @noEscape */ __('Phone Number') ?></span>
                </label>
                <div class="control">
                    <input type="text" name="<?= $block->escapeHtml($code) ?>[address_info][telephone]"
                           value="<?= $block->escapeHtml($card['telephone']) ?>"
                           title="<?= $block->escapeHtml(__('Phone Number')) ?>"
                           class="input-text"
                           id="<?= $block->escapeHtml($code) ?>_phone">
                </div>
            </div>
        </fieldset>
        <fieldset class="fieldset cardparent">
            <legend class="legend"><span><?= /* @noEscape */ __('Card Information') ?></span></legend><br>
            <?php
            if ($block->hasVerification()): ?>
                <div class="field required" id="<?= $block->escapeHtml($code) ?>_cc_type_cvv_div">
                    <label for="<?= $block->escapeHtml($code) ?>_cc_cid" class="label">
                        <span><?= /* @noEscape */ __('Card Verification Number') ?></span>
                    </label>
                    <div class="control">
                        <input type="number"
                               title="<?= /* @noEscape */ __('Card Verification Number') ?>"
                               class="input-text cvv"
                               id="<?= $block->escapeHtml($code) ?>_cc_cid"
                               name="<?= $block->escapeHtml($code) ?>[payment_info][cc_cid]"
                               value=""
                               data-validate='{"required-number":true}' />
                        <?php $_content = '<img src=\"'
                            . $block->getViewFileUrl('Magento_Checkout::cvv.png')
                            . '\" alt=\"'
                            . __('Card Verification Number Visual Reference')
                            . '\" title=\"'
                            . __('Card Verification Number Visual Reference')
                            . '\" />'; ?>
                        <div class="note">
                            <a href="#" class="action cvv"
                               title="<?= /* @noEscape */ __('What is this?') ?>"
                               data-mage-init='{"tooltip": {"content": "<?= /* @noEscape */ $_content ?>"}}'>
                                <span><?= /* @noEscape */ __('What is this?') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="field">
                <label class="label" for="<?= $block->escapeHtml($code) ?>_cc_action">
                    <?= $block->escapeHtml(__('Select Card')) ?>
                </label>
                <div class="control">
                    <select id="<?= $block->escapeHtml($code) ?>_cc_action"
                            name="<?= $block->escapeHtml($code) ?>[payment_info][cc_action]" title="" class="">
                        <option value="existing" selected="selected">
                            <?= $block->escapeHtml('Continue using card XXXXXX-'.$card['cc_last_4']) ?>
                        </option>
                        <option value="new"><?= $block->escapeHtml(__("Update credit card details.")) ?></option>
                    </select>
                </div>
            </div>
            <div class="<?= $block->escapeHtml($code) ?>_new required field required" style="display:none;">
                <label class="label" for="<?= $block->escapeHtml($code) ?>_cc_type">
                    <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
                </label>
                <div class="control">
                    <select id="<?= $block->escapeHtml($code) ?>_cc_type"
                            name="<?= $block->escapeHtml($code) ?>[payment_info][cc_type]"
                            title="<?= $block->escapeHtml(__('Credit Card Type')) ?>"
                            class="validate-select"
                            data-validate='{"validate-cc-type-select":"#<?= /* @noEscape */ $block->escapeHtml($code) ?>_cc_number"}'>
                        <option value=""><?= $block->escapeHtml(__('--Please Select--')) ?></option>
                        <?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                            <option value="<?= $block->escapeHtml($_typeCode) ?>"><?= /* @noEscape */ $_typeName ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_new required" style="display:none;">
                <label for="<?= $block->escapeHtml($code) ?>_cc_number" class="label">
                    <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
                </label>
                <div class="control">
                    <input type="number"
                           id="<?= $block->escapeHtml($code) ?>_cc_number"
                           name="<?= $block->escapeHtml($code) ?>[payment_info][cc_number]"
                           title="<?= $block->escapeHtml(__('Credit Card Number')) ?>"
                           class="input-text"
                           value=""
                           data-validate='{"required-number":true, "validate-cc-number":"#<?= $block->escapeHtml($code) ?>_cc_type", "validate-cc-type":"#<?= $block->escapeHtml($code) ?>_cc_type"}'/>
                </div>
            </div>
            <div class="field <?= $block->escapeHtml($code) ?>_new required"
                 id="<?= $block->escapeHtml($code) ?>_cc_type_exp_div"
                 style="display:none;">
                <label for="<?= $block->escapeHtml($code) ?>_expiration" class="label">
                    <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
                </label>
                <div class="input-box">
                    <div class="field no-label month v-fix" style="margin-right:10px">
                        <div class="control">
                            <select id="<?= $block->escapeHtml($code) ?>_expiration"
                                    name="<?= $block->escapeHtml($code) ?>[payment_info][cc_exp_month]"
                                    class="select month"
                                    data-validate='{required:true, "validate-cc-exp":"#<?= $block->escapeHtml($code) ?>_expiration_yr"}'>
                                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                                    <option value="<?= /* @noEscape */ $k ? $k : '' ?>">
                                        <?= /* @noEscape */ $v ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    <div class="field no-label year v-fix">
                        <div class="control">
                            <select id="<?= $block->escapeHtml($code) ?>_expiration_yr"
                                    name="<?= $block->escapeHtml($code) ?>[payment_info][cc_exp_year]"
                                    class="select year"
                                    data-validate='{required:true}'>
                                <?php foreach ($block->getCcYears() as $k => $v): ?>
                                    <option value="<?= /* @noEscape */ $k ? $k : '' ?>"><?= /* @noEscape */ $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="button"
                        onclick="saveCardForm()"
                        id="cim_update_card_btn"
                        class="action save primary"
                        data-action="save-card"
                        title="<?= $block->escapeHtml(__('Save Card')) ?>">
                    <span><?= $block->escapeHtml(__('Save Card')) ?></span>
                </button>
            </div>
            <input type="hidden" name="<?= $block->escapeHtml($code) ?>[card_mode]" value="add" />
            <input type="hidden"
                   id="<?= $block->escapeHtml($code) ?>_data_value"
                   name="<?= $block->escapeHtml($code) ?>[payment_info][data_value]"
                   value="" />
            <input type="hidden"
                   id="<?= $block->escapeHtml($code) ?>_data_descriptor"
                   name="<?= $block->escapeHtml($code) ?>[payment_info][data_descriptor]"
                   value="" />
            <input type="hidden" name="<?= $block->escapeHtml($block->escapeHtml($code)) ?>[card_id]"
                   value="<?= $block->escapeHtml($card['card_id']) ?>" />
            <input type="hidden"
                   name="<?= $block->escapeHtml($code) ?>[payment_profile_id]"
                   value="<?= $block->escapeHtml($card['payment_profile_id']) ?>" />
            <input type="hidden"
                   name="<?= $block->escapeHtml($code) ?>[card_number_masked]"
                   value="<?= $block->escapeHtml($card['cc_last_4'])?>" />
            <div class="secondary">
                <a class="back" href="<?= $block->escapeHtml($block->getBackUrl()) ?>">
                    <span><?= $block->escapeHtml(__('Go back')) ?></span>
                </a>
            </div>
        </div>
    </form>
<?php } ?>
<script>
    function saveCardForm()
    {
        var dataForm = jQuery('#form-validate');
        dataForm.mage('validation');
        if (jQuery('#form-validate').valid()) {
            jQuery('#cim_update_card_btn').attr('disabled',true);
            <?php
            if ((int) $block->canacceptjs()): ?>
            var selectedVal = jQuery('#<?= $block->escapeHtml($code) ?>_cc_action').val();
            if(selectedVal=='existing') {
                jQuery('#form-validate').submit();
            } else {
                sendPaymentDataToAnet();
            }
            <?php else: ?>
            jQuery('#form-validate').submit();
            <?php endif; ?>
        }
    }
    require(['jquery'], function ($) {
        $('#<?= $block->escapeHtml($code) ?>_cc_action').on('change',function(event){
            var selectedValue = $(this).val();
            switch(selectedValue){
                case 'existing':
                    jQuery('#<?= /* @noEscape */ $code ?>_cc_type').disabled = true;
                    jQuery('#<?= /* @noEscape */ $code ?>_cc_number').disabled = true;
                    jQuery('#<?= /* @noEscape */ $code ?>_expiration').disabled = true;
                    jQuery('#<?= /* @noEscape */ $code ?>_expiration_yr').disabled = true;
                    if(jQuery('#<?= /* @noEscape */ $code ?>_cc_cid') != null){
                        jQuery('#<?= /* @noEscape */ $code ?>_cc_cid').removeClass("validate-cc-cvn");
                        jQuery('#<?= /* @noEscape */ $code ?>_cc_cid').disabled = true;
                    }
                    jQuery('#<?= /* @noEscape */ $code ?>_cc_number').addClass("disabled");
                    jQuery('#<?= /* @noEscape */ $code ?>_expiration').addClass("disabled");
                    jQuery('#<?= /* @noEscape */ $code ?>_expiration_yr').addClass("disabled");
                    jQuery(".<?= /* @noEscape */ $code ?>_new").hide();
                    break;
                case 'new':
                    jQuery('#<?= /* @noEscape */ $code ?>_cc_type').disabled = false;
                    jQuery('#<?= /* @noEscape */ $code ?>_cc_number').disabled = false;
                    jQuery('#<?= /* @noEscape */ $code ?>_expiration').disabled = false;
                    jQuery('#<?= /* @noEscape */ $code ?>_expiration_yr').disabled = false;
                    if(jQuery('#<?= /* @noEscape */ $code ?>_cc_cid') != null){
                        jQuery('#<?= /* @noEscape */ $code ?>_cc_cid').addClass("validate-cc-cvn");
                        jQuery('#<?= /* @noEscape */ $code ?>_cc_cid').disabled = false;
                    }
                    jQuery('#<?= /* @noEscape */ $code ?>_cc_type').removeClass("disabled");
                    jQuery('#<?= /* @noEscape */ $code ?>_cc_number').removeClass("disabled");
                    jQuery('#<?= /* @noEscape */ $code ?>_expiration').removeClass("disabled");
                    jQuery('#<?= /* @noEscape */ $code ?>_expiration_yr').removeClass("disabled");
                    jQuery(".<?= /* @noEscape */ $code ?>_new").show();
                    break;
            }
        });
    });
    function sendPaymentDataToAnet() {
        var secureData = {}, authData = {}, cardData = {};
        cardData.cardNumber = jQuery('#<?= /* @noEscape */ $code ?>_cc_number').val();
        cardData.month = jQuery('#<?= /* @noEscape */ $code ?>_expiration').val();
        cardData.year = jQuery('#<?= /* @noEscape */ $code ?>_expiration_yr').val();
        <?php if ($block->hasVerification()): ?>
        cardData.cardCode = jQuery('#<?= /* @noEscape */ $code ?>_cc_cid').val();
        <?php endif; ?>
        secureData.cardData = cardData;
        authData.clientKey = '<?= /* @noEscape */ $block->getClientKey(); ?>';
        authData.apiLoginID = '<?= /* @noEscape */ $block->getApiLoginId(); ?>';
        secureData.authData = authData;
        Accept.dispatchData(secureData, 'responseHandler');
    }

    function responseHandler(response) {
        if (response.messages.resultCode === 'Error') {
            for (var i = 0; i < response.messages.message.length; i++) {
                console.log(response.messages.message[i].code + ':' + response.messages.message[i].text);
            }
        } else {
            useOpaqueData(response.opaqueData)
        }
    }

    function useOpaqueData(responseData) {
        // This is where you would set the data descriptor & data value to be posted back to your server
        jQuery('#md_authorizecim_data_value').val(responseData.dataValue);
        jQuery('#md_authorizecim_data_descriptor').val(responseData.dataDescriptor);
        jQuery('#form-validate').submit();
    }
</script>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ ($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#<?= /* @noEscape */ $code ?>_region_id",
                "regionInputId": "#<?= /* @noEscape */ $code ?>_region",
                "postcodeId": "#<?= /* @noEscape */$code ?>_zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $block->helper(Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */  $card['region_id'] === null ? 0 : $card['region_id']; ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $block->helper(Magento\Dirassectory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
// @codingStandardsIgnoreEnd
