<?php
// @codingStandardsIgnoreStart
/**
 * @var $block Magedelight\Authorizecim\Block\Adminhtml\CardForm
 */
$code = \Magedelight\Authorizecim\Model\Payment::METHOD_CODE;
?>

<?php $card = $block->getCard(); ?>

<?php
$action = 'add';
$firstName = '';
$lastName = '';
$streetAddress = '';
$city = '';
$telephone = '';
$fax = '';
$company = '';
$regionId = '';
$countryId = null;
$ccLastFour = '';
$postCode = '';
$customerPaymentProfile = '';
$state = '';
$websiteId = '';

if ($card !== null) {
    $action = 'edit';
    if ($card['region_id']) {
        $regionId = $card["region_id"];
    }
    if ($card['state']) {
        $state = $card["state"];
    }
    if (isset($card['country_id'])) {
        $countryId = $card['country_id'];
    }
    if (isset($card['firstname'])) {
        $firstName = $card['firstname'];
    }
    if (isset($card['lastname'])) {
        $lastName = $card['lastname'];
    }
    if (isset($card['street'])) {
        $streetAddress = $card['street'];
    }
    if (isset($card['city'])) {
        $city = $card['city'];
    }

    if (isset($card['postcode'])) {
        $postCode = $card['postcode'];
    }
    if (isset($card['cc_last_4'])) {
        $ccLastFour = $card['cc_last_4'];
    }
    if (isset($card['telephone'])) {
        $telephone = $card['telephone'];
    }
    if (isset($card['company'])) {
        $company = $card['company'];
    }
    if (isset($card['payment_profile_id'])) {
        $customerPaymentProfile = $card['payment_profile_id'];
    }
    if (isset($card['website_id'])) {
        $websiteId = $card['website_id'];
    }
}
?>
<form action="" method="post" id="cim-form-validate" data-mage-init='{"validation":{}}' class="admin__fieldset">
    <?php if ($card !== null) { ?>
        <input type="hidden" id="= $block->escapeHtml(code )?>_card_id" name="<?= $block->escapeHtml($code) ?>[card_id]"
               value="<?= $block->escapeHtml($card['card_id']) ?>"/>
    <?php } ?>
    <div class="admin__field _required">
        <label class="admin__field-label">
            <span><?= $block->escapeHtml(__('First Name')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" name="<?= $block->escapeHtml($code) ?>[address_info][firstname]"
                   class="admin__control-text required-entry"
                   id="<?= $block->escapeHtml($code) ?>_firstname"
                   value="<?= $block->escapeHtml($firstName) ?>"/>
        </div>
    </div>
    <div class="admin__field _required">
        <label class="admin__field-label"><span><?= /* @noEscape */ __('Last Name') ?></span></label>
        <div class="admin__field-control">
            <input type="text"
                   name="<?= $block->escapeHtml($code) ?>[address_info][lastname]"
                   class="admin__control-text required-entry"
                   id="<?= $block->escapeHtml(code)?>_lastname"
                   value="<?= $block->escapeHtml($lastName) ?>"/>
        </div>
    </div>
    <div class="admin__field">
        <label class="admin__field-label">
            <span><?= /* @noEscape */ __('Company') ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text"
                   name="<?= $block->escapeHtml(code)?>[address_info][company]"
                   class="admin__control-text"
                   id="<?= $block->escapeHtml(code)?>_company"
                   value="<?= $block->escapeHtml($company) ?>"/>
        </div>
    </div>
    <div class="admin__field _required">
        <label class="admin__field-label"><span><?= /* @noEscape */ __('Street Address') ?></span></label>
        <div class="admin__field-control">
            <input type="text"
                   name="<?= $block->escapeHtml(code)?>[address_info][street]"
                   class="admin__control-text required-entry"
                   id="<?= $block->escapeHtml(code)?>_street"
                   value="<?= $block->escapeHtml($streetAddress) ?>"/>
        </div>
    </div>
    <div class="admin__field _required">
        <label class="admin__field-label">
            <span><?= /* @noEscape */ __('City') ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text"
                   name="<?= $block->escapeHtml(code)?>[address_info][city]"
                   class="admin__control-text required-entry"
                   id="<?= $block->escapeHtml(code)?>_city"
                   value="<?= $block->escapeHtml($city) ?>"/>
        </div>
    </div>
    <div class="admin__field state-required">
        <label class=""><span class="required">*</span>
            <span><?= /* @noEscape */ __('State/Province') ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= $block->escapeHtml(code)?>_region_id"
                    name="<?= $block->escapeHtml(code)?>[address_info][region_id]"
                    class="admin__control-select">
                <option value=""><?= /* @noEscape */ __('Please select a region, state or province.') ?></option>
            </select>
            <input type="text"
                   id="<?= $block->escapeHtml(code)?>_region"
                   name="<?= $block->escapeHtml(code)?>[address_info][region]"
                   value="<?= $block->escapeHtml($state) ?>"
                   title="<?= /* @noEscape */ __('State/Province') ?>"
                   class="input-text "/>
        </div>
    </div>
    <div class="admin__field _required">
        <label class="admin__field-label"><span><?= /* @noEscape */ __('Zip/Postal Code') ?></span></label>
        <div class="admin__field-control">
            <input type="text"
                   name="<?= $block->escapeHtml(code)?>[address_info][postcode]"
                   class="admin__control-text required-entry"
                   id="<?= $block->escapeHtml(code)?>_postcode"
                   value="<?= $block->escapeHtml($postCode) ?>"/>
        </div>
    </div>
    <div class="admin__field _required">
        <label class="admin__field-label">
            <span><?= /* @noEscape */ __('Country') ?></span>
        </label>
        <div class="admin__field-control">
            <?= $block->getCountryHtmlSelect($countryId, $code . '[address_info][country_id]', $code . '_country_id') ?>
        </div>
    </div>
    <div class="admin__field _required">
        <label class="admin__field-label">
            <span><?= /* @noEscape */ __('Telephone') ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text"
                   name="<?= $block->escapeHtml(code)?>[address_info][telephone]"
                   class="admin__control-text required-entry"
                   id="<?= $block->escapeHtml(code)?>_telephone"
                   value="<?= $block->escapeHtml($telephone) ?>"/>
        </div>
    </div>
    <div class="admin__field _required">
        <label class="admin__field-label">
            <span><?= /* @noEscape */ __('Website') ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= $block->escapeHtml(code)?>_website_id"
                    name="<?= $block->escapeHtml(code)?>[address_info][website_id]"
                    class="admin__control-select required-entry">
                <?php foreach ($block->getWebsitesList() as $website): ?>
                    <?php $selected = ($website['value'] == $websiteId) ? "selected" : ""; ?>
                    <option value="<?= $block->escapeHtml($website['value']) ?>" <?= $block->escapeHtml($selected) ?>>
                        <?= /* @noEscape */ $website['label'] ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <?php if ($block->hasVerification()): ?>
        <div class="admin__field _required">
            <label class="admin__field-label"><span><?= /* @noEscape */ __('Card Verification Number') ?></span></label>
            <div class="admin__field-control">
                <input type="text"
                       name="<?= $block->escapeHtml(code)?>[payment_info][cc_cid]"
                       class="admin__control-text"
                       id="<?= $block->escaeHtml(code)?>_cc_cid"
                       value=""/>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($card === null): ?>
        <div class="admin__field _required">
            <label class="admin__field-label"><span><?= /* @noEscape */ __('Credit Card Type') ?></span></label>
            <div class="admin__field-control">
                <select id="<?= $block->escapeHtml($code) ?>_cc_type"
                        name="<?= $block->escapeHtml(code)?>[payment_info][cc_type]"
                        class="admin__control-select required-entry validate-cc-type-select">
                    <option value=""><?= /* @noEscape */ __('--Please Select--') ?></option>
                    <?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?= $block->escapeHtml($_typeCode) ?>">
                            <?= $block->escapeHtml($_typeName) ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="admin__field _required">
            <label class="admin__field-label"><span><?= /* @noEscape */ __('Credit Card Number') ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="<?= $block->escapeHtml(code)?>[payment_info][cc_number]"
                       class="admin__control-text validate-cc-number validate-cc-type"
                       id="<?= $block->escapeHtml(code)?>_cc_number" value=""/>
            </div>
        </div>
        <div class="admin__field _required">
            <label class="admin__field-label">
                <span><?= /* @noEscape */ __('Credit Card Type') ?></span>
            </label>
            <div class="admin__field-control">
                <select id="<?= $block->escapeHtml($code) ?>_expiration"
                        name="<?= $block->escapeHtml(code)?>[payment_info][cc_exp_month]"
                        class="admin__control-select admin__control-select-month month validate-cc-exp required-entry">
                    <?php foreach ($block->getCcMonths() as $k => $v): ?>
                        <option value="<?= /* @noEscape */ $k ? $k : '' ?>"><?= /* @noEscape */ $v ?></option>
                    <?php endforeach ?>
                </select>
                <select id="<?= $block->escapeHtml($code) ?>_expiration_yr"
                        name="<?= $block->escapeHtml(code)?>[payment_info][cc_exp_year]"
                        class="admin__control-select admin__control-select-year year required-entry">
                    <?php foreach ($block->getCcYears() as $k => $v): ?>
                        <option value="<?= /* @noEscape */ $k ? $k : '' ?>"><?= /* @noEscape */ $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    <?php else: ?>
        <div class="admin__field _required">
            <label class="admin__field-label"><span><?= /* @noEscape */ __('Select Card') ?></span></label>
            <div class="admin__field-control">
                <select id="<?= $block->escapeHtml($code) ?>_cc_action"
                        name="<?= $block->escapeHtml(code)?>[payment_info][cc_action]"
                        class="admin__control-select">
                    <option value="existing"
                            selected="selected">
                        <?= /* @noEscape */ __("Continue using card %1", $ccLastFour); ?>
                    </option>
                    <option value="new"><?= /* @noEscape */ __("Update credit card details.") ?></option>
                </select>
            </div>
        </div>
        <div id="cards-edit-option" class="admin__fieldset">
            <div class="admin__field _required">
                <label class="admin__field-label"><span><?= /* @noEscape */ __('Credit Card Type') ?></span></label>
                <div class="admin__field-control">
                    <select id="<?= $block->escapeHtml($code) ?>_cc_type"
                            name="<?= $block->escapeHtml(code)?>[payment_info][cc_type]"
                            class="admin__control-select">
                        <option value=""><?= /* @noEscape */ __('--Please Select--') ?></option>
                        <?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                            <option value="<?= $block->escapeHtml($_typeCode) ?>">
                                <?= $block->escapeHtml($_typeName) ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
            <div class="admin__field _required">
                <label class="admin__field-label">
                    <span><?= /* @noEscape */ __('Credit Card Number') ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="<?= $block->escapeHtml(code)?>[payment_info][cc_number]"
                           class="admin__control-text"
                           id="<?= $block->escapeHtml(code)?>_cc_number"
                           value=""/>
                </div>
            </div>
            <div class="admin__field _required">
                <label class="admin__field-label">
                    <span><?= /* @noEscape */ __('Credit Card Type') ?></span>
                </label>
                <div class="admin__field-control">
                    <select id="<?= $block->escapeHtml($code) ?>_expiration"
                            name="<?= $block->escapeHtml(code)?>[payment_info][cc_exp_month]"
                            class="admin__control-select admin__control-select-month">
                        <?php foreach ($block->getCcMonths() as $k => $v): ?>
                            <option value="<?= /* @noEscape */ $k ? $k : '' ?>"><?= /* @noEscape */ $v ?></option>
                        <?php endforeach ?>
                    </select>
                    <select id="<?= $block->escapeHtml($code) ?>_expiration_yr"
                            name="<?= $block->escapeHtml(code)?>[payment_info][cc_exp_year]"
                            class="admin__control-select admin__control-select-year">
                        <?php foreach ($block->getCcYears() as $k => $v): ?>
                            <option value="<?= /* @noEscape */ $k ? $k : '' ?>"><?= /* @noEscape */ $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <input type="hidden"
           id="<?= $block->escapeHtml($code) ?>_card_number_masked"
           name="<?= $block->escapeHtml($code) ?>[card_number_masked]"
           value="<?= $block->escapeHtml($ccLastFour) ?>"/>
    <input type="hidden"
           id="<?= $block->escapeHtml($code) ?>_payment_profile_id"
           name="<?= $block->escapeHtml($code) ?>[payment_profile_id]"
           value="<?= $block->escapeHtml($customerPaymentProfile) ?>"/>
</form>
<div class="admin__field">
    <div class="admin__field-control">
        <?php if ($card !== null): ?>
            <button class="button" type="button" onclick="cimupdateCardFromList();">
            <span>
                <span><?= /* @noEscape */ __("Update") ?></span>
            </span>
            </button>
        <?php else: ?>
            <button class="button" type="button" onclick="cimsaveCardFromList();">
            <span>
                <span><?= /* @noEscape */ __("Save") ?></span>
            </span>
            </button>
        <?php endif; ?>
        <a href="#" onclick="addNewCimForm();return false;"><?= /* @noEscape */ __("Cancel") ?></a>
    </div>
</div>
<script type="text/javascript">
    require(["prototype", "mage/adminhtml/form"], function () {
        $('<?= /* @noEscape */ $code ?>_region_id').setAttribute('defaultValue', "<?= /* @noEscape */ $regionId ?>");
        new regionUpdater(<?= /* @noEscape */ $code ?>_country_id, <?= /* @noEscape */ $code ?>_region, <?= /* @noEscape */ $code ?>_region_id, <?= /* @noEscape */ $block->helper(Magento\Directory\Helper\Data::class)->getRegionJson() ?>);
    });
    <?php if ($card !== null): ?>
    require(['jquery'], function ($) {
        $('#cards-edit-option').hide();
        $('#<?= /* @noEscape */ $code ?>_cc_action').on('change', function (event) {
            if ($(this).val() == 'existing') {
                $('#cards-edit-option').hide();
                jQuery("#<?= /* @noEscape */ $code ?>_cc_type").removeClass("required-entry validate-cc-type-select");
                jQuery("#<?= /* @noEscape */ $code ?>_cc_number").removeClass("validate-cc-number validate-cc-type");
                jQuery("#<?= /* @noEscape */ $code ?>_expiration").removeClass("month validate-cc-exp required-entry");
                jQuery("#<?= /* @noEscape */ $code ?>_expiration_yr").removeClass("year required-entry");
                if (jQuery('#<?= /* @noEscape */ $code ?>_cc_cid')) {
                    jQuery("#<?= /* @noEscape */ $code ?>_cc_cid").removeClass("cvv required-entry validate-cc-cvn");
                }
            } else {
                $('#cards-edit-option').show();

                jQuery("#<?= /* @noEscape */ $code ?>_cc_type").addClass("required-entry validate-cc-type-select");
                jQuery("#<?= /* @noEscape */ $code ?>_cc_number").addClass("validate-cc-number validate-cc-type");
                jQuery("#<?= /* @noEscape */ $code ?>_expiration").addClass("month validate-cc-exp required-entry");
                jQuery("#<?= /* @noEscape */ $code ?>_expiration_yr").addClass("year required-entry");
                if (jQuery('#<?= /* @noEscape */ $code ?>_cc_cid')) {
                    jQuery("#<?= /* @noEscape */ $code ?>_cc_cid").addClass("cvv required-entry validate-cc-cvn");
                }
            }
        });
    });
    <?php endif; ?>
    var cvvcheck = 0;
    var cs_cardSaveAjaxUrl = '<?= /* @noEscape */ $block->getUrl("md_authorizecim/cards/save", ["id" => $block->getCustomer()->getId()]) ?>';
    var cs_cardUpdateAjaxUrl = '<?= /* @noEscape */ $block->getUrl("md_authorizecim/cards/update", ["id" => $block->getCustomer()->getId()]) ?>';
    <?php if ($block->hasVerification()): ?>
    cvvcheck = 1;
    <?php endif; ?>

    function cimsaveCardFromList() {
        var formToValidate = $('cim-form-validate');
        var validator = new Validation(formToValidate);
        if (validator.validate()) {

            // var maskedCard = $$('#md-cybersource-card-form input[name="<?= /* @noEscape */ $code ?>[card_number_masked]"]')[0];
            var paymentParam = {
                firstname: jQuery('#<?= /* @noEscape */ $code ?>_firstname').val(),
                lastname: jQuery('#<?= /* @noEscape */ $code ?>_lastname').val(),
                company: jQuery('#<?= /* @noEscape */ $code ?>_company').val(),
                street: jQuery('#<?= /* @noEscape */ $code ?>_street').val(),
                city: jQuery('#<?= /* @noEscape */ $code ?>_city').val(),
                region_id: jQuery('#<?= /* @noEscape */ $code ?>_region_id').val(),
                state: jQuery('#<?= /* @noEscape */ $code ?>_region').val(),
                postcode: jQuery('#<?= /* @noEscape */ $code ?>_postcode').val(),
                country_id: jQuery('#<?= /* @noEscape */ $code ?>_country_id').val(),
                telephone: jQuery('#<?= /* @noEscape */ $code ?>_telephone').val(),
                cc_type: jQuery('#<?= /* @noEscape */ $code ?>_cc_type').val(),
                cc_number: jQuery('#<?= /* @noEscape */ $code ?>_cc_number').val(),
                cc_exp_month: jQuery('#<?= /* @noEscape */ $code ?>_expiration').val(),
                cc_exp_year: jQuery('#<?= /* @noEscape */ $code ?>_expiration_yr').val(),
                cc_cid: (jQuery('#<?= /* @noEscape */ $code ?>_cc_cid')) ? jQuery('#<?= /* @noEscape */ $code ?>_cc_cid').val() : '',
                card_number_masked: jQuery('#<?= /* @noEscape */ $code ?>_card_number_masked').val(),
                payment_profile_id: jQuery('#<?= /* @noEscape */ $code ?>_payment_profile_id').val(),
                website_id: jQuery('#<?= /* @noEscape */ $code ?>_website_id').val(),
            };

            jQuery.ajax('' + cs_cardSaveAjaxUrl + '?isAjax=true', {
                data: {paymentParam, form_key: jQuery("input[name=form_key]").val()},
                method: 'POST',
                dataType: 'json',
                beforeSend: function () {
                    jQuery('.admin__data-grid-loading-mask').show();
                    jQuery('.admin__data-grid-loading-mask').css("position", "fixed");
                },
                complete: function (transport) {
                    jQuery('#messages').remove();
                    var resultData = transport.responseText.evalJSON();
                    if (!resultData.error) {
                        jQuery('#md-cim-cards-list-container').parent().html(resultData.carddata);
                    }
                    jQuery('.page-main-actions').after(resultData.message);
                    jQuery('.admin__data-grid-loading-mask').hide();
                    jQuery('.admin__data-grid-loading-mask').css("position", "absolute");
                },
                error: function (transport) {
                    jQuery('.page-main-actions').after('Error during processing...');
                },

            });


        }
    }

    function cimupdateCardFromList() {

        var formToValidate = $('cim-form-validate');
        var validator = new Validation(formToValidate);
        if (validator.validate()) {
            var ccAction = jQuery('#<?= /* @noEscape */ $code ?>_cc_action');
            var paymentParam = {
                card_id: jQuery('#<?= /* @noEscape */ $code ?>_card_id').val(),
                customer_id: jQuery('#<?= /* @noEscape */ $code ?>_customer_id').val(),
                cc_type: jQuery('#<?= /* @noEscape */ $code ?>_cc_type').val(),
                cc_number: jQuery('#<?= /* @noEscape */ $code ?>_cc_number').val(),
                cc_exp_month: jQuery('#<?= /* @noEscape */ $code ?>_expiration').val(),
                cc_exp_year: jQuery('#<?= /* @noEscape */ $code ?>_expiration_yr').val(),
                cc_cid: (jQuery('#<?= /* @noEscape */ $code ?>_cc_cid')) ? jQuery('#<?= /* @noEscape */ $code ?>_cc_cid').val() : '',
                firstname: jQuery('#<?= /* @noEscape */ $code ?>_firstname').val(),
                lastname: jQuery('#<?= /* @noEscape */ $code ?>_lastname').val(),
                company: jQuery('#<?= /* @noEscape */ $code ?>_company').val(),
                street: jQuery('#<?= /* @noEscape */ $code ?>_street').val(),
                city: jQuery('#<?= /* @noEscape */ $code ?>_city').val(),
                region_id: jQuery('#<?= /* @noEscape */ $code ?>_region_id').val(),
                state: jQuery('#<?= /* @noEscape */ $code ?>_region').val(),
                postcode: jQuery('#<?= /* @noEscape */ $code ?>_postcode').val(),
                country_id: jQuery('#<?= /* @noEscape */ $code ?>_country_id').val(),
                telephone: jQuery('#<?= /* @noEscape */ $code ?>_telephone').val(),
                cc_action: jQuery('#<?= /* @noEscape */ $code ?>_cc_action').val(),
                card_number_masked: jQuery('#<?= /* @noEscape */ $code ?>_card_number_masked').val(),
                payment_profile_id: jQuery('#<?= /* @noEscape */ $code ?>_payment_profile_id').val(),
                website_id: jQuery('#<?= /* @noEscape */ $code ?>_website_id').val(),
            };
            if ($('<?= /* @noEscape */ $code ?>_cc_cid') == null) {
                delete paymentParam.cc_cid;
            }


            jQuery.ajax('' + cs_cardUpdateAjaxUrl + '?isAjax=true', {
                data: {paymentParam, form_key: jQuery("input[name=form_key]").val()},
                method: 'POST',
                dataType: 'json',
                beforeSend: function () {
                    jQuery('.admin__data-grid-loading-mask').show();
                    jQuery('.admin__data-grid-loading-mask').css("position", "fixed");
                },
                complete: function (transport) {
                    jQuery('#messages').remove();
                    var resultData = transport.responseText.evalJSON();
                    if (!resultData.error) {
                        jQuery('#md-cim-cards-list-container').parent().html(resultData.carddata);
                    }
                    jQuery('.page-main-actions').after(resultData.message);
                    jQuery('.admin__data-grid-loading-mask').hide();
                    jQuery('.admin__data-grid-loading-mask').css("position", "absolute");

                },
                error: function (transport) {
                    jQuery('.page-main-actions').after('Error during processing...');
                },

            });
        }

    }
</script>
// @codingStandardsIgnoreEnd
