<?php
$order = $block->getOrder();
?>
<?php if ($block->getOrder()->getDistributorOrderNumber()): ?>
    <section class="admin__page-section distributor-info">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('Distributor Info')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-billing-address">
                <div class="admin__page-section-item-title" style="margin-top: 10px;">
                    <span class="title"><?= $block->escapeHtml(__('General Info')) ?></span>
                    <table class="admin__table-secondary order-information-table">
                        <tr>
                            <th><?= $block->escapeHtml(__('Distributor')) ?></th>
                            <td><?= $block->escapeHtml(__($block->getDistributorName())) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Order Number')) ?></th>
                            <td><?= $block->escapeHtml($block->getOrder()->getDistributorOrderNumber()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Order Status')) ?></th>
                            <td><?= $block->escapeHtml($block->getOrder()->getDistributorOrderStatus()) ?></td>
                        </tr>
                    </table>
                </div>
                <?php if (!empty($block->getTrackingInfo())): ?>
                    <div class="admin__page-section-item-title" style="margin-top: 10px;">
                        <span class="title"><?= $block->escapeHtml(__('Tracking Info')) ?></span>
                        <table class="admin__table-secondary order-information-table">
                            <tr>
                                <th><?= $block->escapeHtml(__('Carrier')) ?></th>
                                <th><?= $block->escapeHtml(__('Tracking Number')) ?></th>
                            </tr>
                            <?php foreach ($block->getTrackingInfo() as $tracking_info):?>
                                <tr>
                                    <th><?= $block->escapeHtml($tracking_info['provider']) ?></th>
                                    <th><?= $block->escapeHtml($tracking_info['tracking_number']) ?></th>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                <?php endif; ?>
            </div>
            <?php if (!empty($block->getProvisionInfo())): ?>
                <div class="admin__page-section-item order-billing-address" style="margin-left: 60px;">
                    <div class="admin__page-section-item-title" style="margin-top: 10px;">
                        <span class="title"><?= $block->escapeHtml(__('Macs / Serial Numbers')) ?></span>
                        <table class="admin__table-secondary order-information-table">
                            <tr>
                                <th><?= $block->escapeHtml(__('Sku')) ?></th>
                                <th><?= $block->escapeHtml(__('Mac')) ?></th>
                                <th><?= $block->escapeHtml(__('Serial')) ?></th>
                            </tr>
                            <?php foreach ($block->getProvisionInfo() as $provision_info):?>
                                <tr>
                                    <th><?= $block->escapeHtml($provision_info['sku']) ?></th>
                                    <th><?= $block->escapeHtml($provision_info['mac']) ?></th>
                                    <th><?= $block->escapeHtml($provision_info['serial']) ?></th>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </section>
<?php endif; ?>
